### ISSUE TITLE
DrawText throws System.NotSupportedException: Specified method is not supported.

### ISSUE THREAD

**Issue by gokeiyou** [SixLabors/ImageSharp.Drawing#269]
### Prerequisites

- [X] I have bought a Commercial License
- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

SixLabors.ImageSharp/2.1.3

### Other ImageSharp packages and versions

SixLabors.ImageSharp.Drawing/1.0.0-beta15;Fonts/1.0.0-beta18

### Environment (Operating system, version and so on)

macOS Ventura 13.1

### .NET Framework version

.NET 7

### Description

`Specified method is not supported.      
      ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      System.NotSupportedException: Specified method is not supported.
         at SixLabors.Fonts.Tables.Cff.CffParser.ReadFDArray(BigEndianBinaryReader reader, CidFontInfo cidFontInfo)
         at SixLabors.Fonts.Tables.Cff.CffParser.Load(BigEndianBinaryReader reader, Int64 offset)
         at SixLabors.Fonts.Tables.Cff.Cff1Table.Load(BigEndianBinaryReader reader)
         at SixLabors.Fonts.Tables.Cff.Cff1Table.Load(FontReader fontReader)
         at SixLabors.Fonts.Tables.TableLoader.Load[TTable](FontReader reader)
         at SixLabors.Fonts.FontReader.TryGetTable[TTableType]()
         at SixLabors.Fonts.StreamFontMetrics.LoadCompactFont(FontReader reader)
         at SixLabors.Fonts.StreamFontMetrics.LoadFont(FontReader reader)
         at SixLabors.Fonts.StreamFontMetrics.LoadFont(Stream stream)
         at SixLabors.Fonts.StreamFontMetrics.LoadFont(String path, Int64 offset)
         at SixLabors.Fonts.FileFontMetrics.<>c__DisplayClass3_0.<.ctor>b__0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      --- End of stack trace from previous location ---
         at System.Lazy`1.CreateValue()
         at SixLabors.Fonts.FileFontMetrics.TryGetGlyphId(CodePoint codePoint, Nullable`1 nextCodePoint, UInt16& glyphId, Boolean& skipNextCodePoint)
         at SixLabors.Fonts.TextLayout.DoFontRun(ReadOnlySpan`1 text, Int32 start, IReadOnlyList`1 textRuns, Int32& textRunIndex, Int32& codePointIndex, Int32& bidiRunIndex, Boolean isFallbackRun, Font font, BidiRun[] bidiRuns, Dictionary`2 bidiMap, GlyphSubstitutionCollection substitutions, GlyphPositioningCollection positionings)
         at SixLabors.Fonts.TextLayout.ProcessText(ReadOnlySpan`1 text, TextOptions options)
         at SixLabors.Fonts.TextLayout.GenerateLayout(ReadOnlySpan`1 text, TextOptions options)
         at SixLabors.Fonts.TextRenderer.RenderText(ReadOnlySpan`1 text, TextOptions options)
         at SixLabors.Fonts.TextRenderer.RenderText(String text, TextOptions options)
         at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.BeforeImageApply()
         at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
         at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
         at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
         at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, DrawingOptions drawingOptions, TextOptions textOptions, String text, IBrush brush, IPen pen)
         at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextOptions textOptions, String text, IPen pen)`

### Steps to Reproduce

`IPen pen = new Pen(Color.Black, 2);
var img = new Image<Rgba32>(2000, 180);
            img.Mutate(g =>
            {
                var textFont = font.CreateFont(128);
                var options = new TextOptions(textFont)
                {
                    VerticalAlignment = VerticalAlignment.Center,
                    HorizontalAlignment = HorizontalAlignment.Center,
                    Font = textFont
                };
                
                g.DrawText(options, text, pen);
            });`

**Comment by JimBobSquarePants** [comment]
The stack trace is explicit here indicating that the method within the CFF font parser is not supported. 

You’ll need to provide the font and text.

**Comment by gokeiyou** [comment]
```c#
var font = SystemFonts.Get("PingFang SC");
```
I have read the Font from OS

**Comment by JimBobSquarePants** [comment]
We’ll need it to replicate the issue. Otherwise you’ll have to debug and implement the method yourself.

**Comment by gokeiyou** [comment]
Thank you so much!

**Comment by gokeiyou** [comment]
@JimBobSquarePants I try to use the Windows operating system to call this API, and the result can be returned normally without throwing an exception. But when I use the Mac operating system, this exception is thrown.

**Comment by JimBobSquarePants** [comment]
Windows is likely using a TTF version of the font.

**Comment by gokeiyou** [comment]
I see, I should use generic font files like woff, woff2.  Is it right?

**Comment by JimBobSquarePants** [comment]
Please do not pollute issues with non-related questions. Please use the [discussion channels](https://github.com/SixLabors/ImageSharp.Drawing/discussions/categories/q-a) in the future.

In answer to your actual issue. Yes, you can use alternative font formats but we want to be able to fully support CFF fonts, so we require you to provide us with the font file that is causing issues in order to debug the issue, otherwise you can submit a PR. 

In answer to your second question. The font clearly doesn't contain english characters, you have to provide [fallback font families](https://docs.sixlabors.com/api/Fonts/SixLabors.Fonts.TextOptions.html#SixLabors_Fonts_TextOptions_FallbackFontFamilies).

**Comment by gokeiyou** [comment]
First of all thank you very much for your patience in answering. It's my first time to raise Issues on GitHub. I don't have a good experience. I'm very sorry for the inconvenience. I have successfully solved my problem by carefully reading the API documentation. Thanks again for your help. Thank you so much!
