### ISSUE TITLE
ArgumentOutOfRangeException: Parameter "bufferAlignment" (System.Int32) must be greater than or equal to 0, was -2147483643

### ISSUE THREAD

**Issue by arakis** [SixLabors/ImageSharp.Drawing#54]
Today, I got a bug report from a user of my open source project:

![image](https://user-images.githubusercontent.com/1831942/84065661-01149900-a9c5-11ea-9310-88b342fe6ffd.png)

```
SixLabors.ImageSharp.ImageProcessingException
  HResult=0x80131500
  Message=An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextGraphicsOptions options, String text, Font font, IBrush brush, IPen pen, PointF location)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextGraphicsOptions options, String text, Font font, Color color, PointF location)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, String text, Font font, Color color, PointF location)
   at Aximo.Engine.Components.Geometry.StatsComponent.<>c__DisplayClass4_0.<UpdateFrame>b__1(IImageProcessingContext ctx) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Components\Geometry\StatsComponent.cs:line 42
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at Aximo.Engine.Components.Geometry.StatsComponent.UpdateFrame() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Components\Geometry\StatsComponent.cs:line 42
   at Aximo.Engine.ActorComponent.UpdateFrameInternal() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Components\ActorComponent.cs:line 48
   at Aximo.Engine.SceneComponent.UpdateFrameInternal() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Components\SceneComponent.cs:line 303
   at Aximo.Engine.Actor.UpdateFrameInternal() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Actors\Actor.cs:line 128
   at Aximo.Engine.SceneContext.OnUpdateFrame() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\SceneContext.cs:line 133
   at Aximo.Engine.Application.OnUpdateFrameInternal(FrameEventArgs e) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Application.cs:line 379
   at Aximo.Engine.Application.<RegisterWindowEvents>b__46_1(FrameEventArgs e) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Application.cs:line 144
   at Aximo.Engine.Windows.WindowContext.OnUpdateFrameInternal(FrameEventArgs e) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Windows\WindowContext.cs:line 79
   at OpenToolkit.Windowing.Desktop.GameWindow.OnUpdateFrame(FrameEventArgs args)
   at Aximo.Engine.Windows.RenderWindow.OnUpdateFrame(FrameEventArgs e) in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Windows\RenderWindow.cs:line 81
   at OpenToolkit.Windowing.Desktop.GameWindow.DispatchUpdateFrame()
   at OpenToolkit.Windowing.Desktop.GameWindow.Run()
   at Aximo.Engine.Windows.WindowContext.UIThread() in C:\SOFTWARE_LIBRARIES\AxEngineSource\AxEngine\Engine\Windows\WindowContext.cs:line 202
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

  This exception was originally thrown at this call stack:
	SixLabors.ThrowHelper.ThrowArgumentOutOfRangeException(string, string)
	SixLabors.ThrowHelper.ThrowArgumentOutOfRangeExceptionForMustBeGreaterThanOrEqualTo<T>(T, T, string)
	SixLabors.ImageSharp.Memory.MemoryGroup<T>.Allocate(SixLabors.ImageSharp.Memory.MemoryAllocator, long, int, SixLabors.ImageSharp.Memory.AllocationOptions)
	SixLabors.ImageSharp.Memory.MemoryAllocatorExtensions.AllocateGroup<T>(SixLabors.ImageSharp.Memory.MemoryAllocator, long, int, SixLabors.ImageSharp.Memory.AllocationOptions)
	SixLabors.ImageSharp.Memory.MemoryAllocatorExtensions.Allocate2D<T>(SixLabors.ImageSharp.Memory.MemoryAllocator, int, int, SixLabors.ImageSharp.Memory.AllocationOptions)
	SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor<TPixel>.CachingGlyphRenderer.Render(SixLabors.ImageSharp.Drawing.IPath)
	SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor<TPixel>.CachingGlyphRenderer.EndGlyph()
	SixLabors.Fonts.GlyphInstance.RenderTo(SixLabors.Fonts.IGlyphRenderer, float, System.Numerics.Vector2, System.Numerics.Vector2, float)
	SixLabors.Fonts.TextRenderer.RenderText(System.ReadOnlySpan<char>, SixLabors.Fonts.RendererOptions)
	SixLabors.Fonts.TextRenderer.RenderText(string, SixLabors.Fonts.RendererOptions)
    ...
    [Call Stack Truncated]
Inner Exception 1:
ArgumentOutOfRangeException: Parameter "bufferAlignment" (System.Int32) must be greater than or equal to 0, was -2147483643 (Parameter 'bufferAlignment')
```

Original issue https://github.com/AximoGames/AxEngine/issues/3

SixLabors.ImageSharp: 1.0.0-rc0001
SixLabors.ImageSharp.Drawing: 1.0.0-beta0008

Because this issue don't happen on my own device, I have no idea what could be the problem.

**Comment by pekspro** [comment]
Funny, I run into the same problem playing around with the sample code. Creating pen with:

    Pens.DashDot(Color.White, 0);

or

    Pens.Solid(Color.White, 0);

makes bad thing happen. See sample code below.


        {
            int width = 768;
            int height = 438;

            // Creates a new image with empty pixel data. 
            using (var image = new Image<Rgba32>(width, height))
            {
                {
                    FontCollection collection = new FontCollection();
                    FontFamily family = collection.Install(@"C:\Windows\Fonts\verdana.ttf");
                    Font font = family.CreateFont(48, FontStyle.Bold);

                    // The options are optional
                    TextGraphicsOptions options = new TextGraphicsOptions()
                    {
                        TextOptions = new TextOptions()
                        {
                            ApplyKerning = true,
                            TabWidth = 8, // a tab renders as 8 spaces wide
                            WrapTextWidth = width, // greater than zero so we will word wrap at 100 pixels wide
                            HorizontalAlignment = HorizontalAlignment.Center // right align
                        }
                    };

                    IBrush brush = Brushes.Solid(Color.White);
                    IPen pen = Pens.DashDot(Color.White, 0);  //0 makes application freeze and eat memory
                    // IPen pen = Pens.Solid(Color.White, 0); //0 makes application crash
                    string text = "sample text";

                    // Draw the text
                    image.Mutate(x => x.DrawText(options, text, font, brush, pen, new PointF(0, 100)));
                }

            } // Dispose - releasing memory into a memory pool ready for the next image you wish to process.
        }

**Comment by JimBobSquarePants** [comment]
@pekspro Thanks so much for this, it's invaluable for debugging.

I've been following the  trace using  your second sample with the solid pen to two key areas:

At this Clipper returns an array of zero length. I'm assuming because `width` is `0`.
https://github.com/SixLabors/ImageSharp.Drawing/blob/425bdbd9b4df45dff3baaf70f94b48b28682651d/src/ImageSharp.Drawing/Shapes/Outliner.cs#L222

This array is passed to the `ComplexPolygon` constructor which, since the array has zero length will return bounds containing a combination of `float.Min` and `float.Max`
https://github.com/SixLabors/ImageSharp.Drawing/blob/425bdbd9b4df45dff3baaf70f94b48b28682651d/src/ImageSharp.Drawing/Shapes/ComplexPolygon.cs#L74

This gets translated into an invalid memory allocation request in `DrawTextProcessor<TPixel>`.
https://github.com/SixLabors/ImageSharp.Drawing/blob/425bdbd9b4df45dff3baaf70f94b48b28682651d/src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor%7BTPixel%7D.cs#L374

So... We can see how the error manifests but I'm not sure what the best fix is. Should we be sanitizing the pen width or changing the polygon constructor or something else entirely.

@tocsoft I've created a branch where I've added the sample code as a test so we can work against it. I'll have to take your lead.

https://github.com/SixLabors/ImageSharp.Drawing/tree/bee1775aed96e998c81a699cffafd6392e1b1d14

**Comment by tocsoft** [comment]
Nice investigation.

I feels like both need fixing individually. First I would think we should sanitize Pen widths first, as a width of zero just makes no sense. Then complex polygon should special case the empty array input so that its bounds end up set to `RectangleF.Empty` in case any user code accidently tries the same.
