### ISSUE TITLE
Issue rendering text with brush

### ISSUE THREAD

**Issue by UkooLabs** [SixLabors/ImageSharp.Drawing#97]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Assuming needed expect commercial license was bought under the name PNI Digital Media, not sure how you check.

Drawing of text appears to crash due to any brush error message...

```
SixLabors.ImageSharp.ImageProcessingException
  HResult=0x80131500
  Message=An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor)
   at SixLabors.ImageSharp.Drawing.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextGraphicsOptions options, String text, Font font, IBrush brush, IPen pen, PointF location)
   at RenderPreview.Controllers.TextController.<>c__DisplayClass3_0.<ProcessText>b__0(IImageProcessingContext m) in D:\Git\RenderPreview\RenderPreview\Controllers\TextController.cs:line 54
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at RenderPreview.Controllers.TextController.ProcessText(Image`1 image) in D:\Git\RenderPreview\RenderPreview\Controllers\TextController.cs:line 54
   at RenderPreview.Controllers.TextController.Apply() in D:\Git\RenderPreview\RenderPreview\Controllers\TextController.cs:line 40
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ImageProcessingException: An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail.

Inner Exception 2:
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

```

### Steps to Reproduce

```
            var font = _fontCollection.CreateFont("Open Sans", 200);
            string text = "Hello World Hello World Hello World Hello World Hello World";
            TextGraphicsOptions textGraphicsOptions = new TextGraphicsOptions();
            var brush = Brushes.Horizontal(Color.Red);
            var pen = Pens.Dash(Color.RoyalBlue, 10);
            image.Mutate(m => m.DrawText(textGraphicsOptions, text, font, brush, pen, new PointF(0, 0)));
```

### System Configuration

- ImageSharp.Drawing version:  1.0.0 beta 10
- Other ImageSharp packages and versions: 1.0.1
- Environment (Operating system, version and so on): Win 10
- .NET Framework version: .NetCore 3.1
- Additional information:

**Comment by tocsoft** [comment]
@UkooLabs can you please try the version on myget I believe this issue might have already been resolved.

**Comment by JimBobSquarePants** [comment]
@UkooLabs did you ever get the chance to confirm this? We don't have the context (image dimensions) to confirm this from our end. Thanks!

**Comment by antonfirsov** [comment]
Closing for now since it's most likely fixed, and I'm trying to clean up the backlog. @UkooLabs feel free to reopen (with more contextual info) if it's still an issue.
